# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "op3"
BBFILE_PATTERN_op3 := "^${LAYERDIR}/"
BBFILE_PRIORITY_op3 = "11"

LAYERVERSION_op3 = "1"

LAYERDEPENDS_op3 = "core sunxi openembedded-layer"

LAYERSERIES_COMPAT_op3 = "walnascar"

META_OP3_BASE := "${LAYERDIR}"
